const state={all:[],filtered:[],index:0,category:"ALL",paused:false,manualPaused:false,hoverPaused:false,focus:false,switchMs:7000,timer:null,query:"",sort:"smart"};
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const age=iso=>{if(!iso)return"";const m=Math.floor(Math.max(0,Date.now()-new Date(iso))/60000);return m<60?`${m}分前`:m<1440?`${Math.floor(m/60)}時間前`:`${Math.floor(m/1440)}日前`};
const sourceType=x=>x.source_type==="social"?"X話題":x.official?"公式":"報道";
const sig=x=>x.signal||(x.priority>=5?"HIGH":x.priority>=4?"MEDIUM":"LOW");
function score(x){const h=Math.max(0,(Date.now()-new Date(x.published_at))/3600000),fresh=Math.max(0,36-h),s=sig(x)==="HIGH"?32:sig(x)==="MEDIUM"?16:3,q=x.official?18:x.source_type==="social"?1:7;return(x.score||0)+fresh*.3+s+q+Math.min(10,(x.cluster_count||1)-1)}
function searchable(x){return[x.title,x.title_ja,x.summary_ja,x.why_it_matters,...(x.key_points||[]),x.source,x.category].filter(Boolean).join(" ").toLowerCase()}
function apply(){let a=state.category==="ALL"?[...state.all]:state.all.filter(x=>x.category===state.category);if(state.query)a=a.filter(x=>searchable(x).includes(state.query));if(state.sort==="newest")a.sort((a,b)=>new Date(b.published_at)-new Date(a.published_at));else if(state.sort==="priority")a.sort((a,b)=>(b.priority||0)-(a.priority||0));else a.sort((a,b)=>score(b)-score(a));state.filtered=a;if(state.index>=a.length)state.index=0}
function filters(){const cats=["ALL",...new Set(state.all.map(x=>x.category).filter(Boolean))];$("#filters").innerHTML=cats.map(c=>`<button data-cat="${esc(c)}" class="${c===state.category?"active":""}">${esc(c)}</button>`).join("");$("#filters").querySelectorAll("button").forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;state.index=0;apply();filters();render();resetTimer()})}
function progress(){const b=$("#progressBar");b.classList.remove("run");void b.offsetWidth;b.style.setProperty("--duration",`${state.switchMs/1000}s`);if(!state.paused)b.classList.add("run")}
function setPause(){state.paused=state.manualPaused||state.hoverPaused;document.body.classList.toggle("paused",state.paused);$("#pauseBtn").textContent=state.manualPaused?"Resume":"Pause";resetTimer()}
function image(x){const w=$("#thumbWrap"),im=$("#mainImage");if(!x.image){w.hidden=true;im.removeAttribute("src");return}w.hidden=false;im.src=x.image;$("#thumbCaption").textContent=x.source||"";im.onerror=()=>w.hidden=true}
function keypoints(x){const p=(x.key_points||[]).filter(Boolean).slice(0,3);$("#keyPointSection").hidden=!p.length;$("#keyPoints").innerHTML=p.map(v=>`<li>${esc(v)}</li>`).join("")}
function related(x){const r=(x.related_sources||[]).filter(Boolean);$("#coverageBadge").hidden=(x.cluster_count||1)<=1;$("#coverageBadge").textContent=`関連${x.cluster_count||1}件`;$("#relatedSources").hidden=r.length<2;$("#relatedSources").textContent=r.length>=2?`関連ソース: ${r.slice(0,5).join(" / ")}`:""}
function queue(){const src=state.filtered.length?state.filtered:state.all,out=[],seen=new Set();for(let i=1;i<=src.length&&out.length<7;i++){const q=src[(state.index+i)%src.length];if(q&&!seen.has(q.id)){seen.add(q.id);out.push(q)}}if(out.length<7)for(const q of [...state.all].sort((a,b)=>score(b)-score(a))){if(out.length>=7)break;if(!seen.has(q.id)){seen.add(q.id);out.push(q)}}$("#queue").innerHTML=out.map(q=>`<div class="qitem" data-id="${esc(q.id)}">${q.image?`<img class="qimg" src="${esc(q.image)}">`:`<div class="qph">${q.source_type==="social"?"X":"NEWS"}</div>`}<div><div class="qtop">${esc(q.category)} · ${esc(sig(q))}</div><div class="qtitle">${esc(q.title_ja||q.title)}</div><div class="qmeta">${esc(sourceType(q))} · ${esc(q.source)} · ${esc(age(q.published_at))}</div></div></div>`).join("");$("#queue").querySelectorAll(".qitem").forEach(e=>e.onclick=()=>select(e.dataset.id))}
function select(id){let i=state.filtered.findIndex(x=>x.id===id);if(i<0){state.category="ALL";apply();filters();i=state.filtered.findIndex(x=>x.id===id)}if(i>=0){state.index=i;render();resetTimer()}}
function render(){if(!state.filtered.length){$("#mainTitle").textContent="表示できる記事がありません";return}state.index=(state.index+state.filtered.length)%state.filtered.length;const x=state.filtered[state.index],hasJa=x.title_ja&&x.title_ja.trim()!==x.title?.trim();$("#sourceTypeBadge").textContent=sourceType(x);$("#categoryBadge").textContent=x.category;$("#signalBadge").textContent=sig(x);$("#signalBadge").className=sig(x).toLowerCase();$("#contentBadge").textContent=x.content_status==="full"?"本文取得済":"見出しのみ";$("#contentBadge").className=x.content_status==="full"?"full":"headline";$("#sourceName").textContent=x.source||"";$("#publishedAge").textContent=age(x.published_at);$("#originalTitle").hidden=!hasJa;$("#originalTitle").textContent=hasJa?x.title:"";$("#mainTitle").textContent=x.title_ja||x.title||"";$("#brief").textContent=x.summary_ja||"";$("#brief").hidden=!x.summary_ja;$("#headlineOnly").hidden=x.content_status==="full";keypoints(x);$("#whySection").hidden=!x.why_it_matters;$("#whyItMatters").textContent=x.why_it_matters||"";related(x);$("#openArticle").href=x.url||"#";$("#positionText").textContent=`${state.index+1} / ${state.filtered.length}`;image(x);queue();progress()}
function topstories(){const a=[...state.all].filter(x=>x.source_type!=="social").sort((a,b)=>score(b)-score(a)).slice(0,6);$("#topStories").innerHTML=a.map(x=>`<div class="mini" data-id="${esc(x.id)}"><small>${esc(sourceType(x))} · ${esc(x.category)} · ${esc(sig(x))}</small><b>${esc(x.title_ja||x.title)}</b><small>${esc(x.source)} · ${esc(age(x.published_at))}</small></div>`).join("");$("#topStories").querySelectorAll(".mini").forEach(e=>e.onclick=()=>select(e.dataset.id))}
function social(){const a=state.all.filter(x=>x.source_type==="social").slice(0,4);$("#socialPanel").hidden=false;$("#socialStatus").textContent=a.length?`${a.length}件 · 無料公開Web`:"無料公開Web";$("#socialPulse").innerHTML=a.length?a.map(x=>`<div class="socialitem" data-id="${esc(x.id)}"><small>${esc(x.source)} · ${esc(age(x.published_at))}</small><div>${esc(x.title_ja||x.title)}</div></div>`).join(""):`<div class="socialempty">無料モードでは、検索で取得できた公開X投稿だけ表示します。現在は該当なし。</div>`}
function alert(){const x=[...state.all].filter(x=>sig(x)==="HIGH"&&(Date.now()-new Date(x.published_at)<86400000)).sort((a,b)=>score(b)-score(a))[0];$("#alertStrip").hidden=!x;if(x){$("#alertText").textContent=x.title_ja||x.title;$("#alertOpenBtn").onclick=()=>select(x.id)}}
function resetTimer(){clearInterval(state.timer);if(!state.paused)state.timer=setInterval(()=>{if(state.filtered.length){state.index=(state.index+1)%state.filtered.length;render()}},state.switchMs);progress()}
async function news(){try{const r=await fetch(`./data/news.json?t=${Date.now()}`,{cache:"no-store"}),d=await r.json();state.all=d.items||[];state.switchMs=(d.rotation_seconds||7)*1000;apply();filters();render();topstories();social();alert();$("#feedMeta").textContent=`${state.all.length}件 · ${d.updated_at?new Date(d.updated_at).toLocaleString("ja-JP"):"—"}`;$("#statusText").textContent=`${state.all.length} items · ${d.enriched_count||0} JP titles · ${d.fulltext_enriched_count||d.content_extracted_count||0} full-text · ${d.semantic_merged_count||0} merged`;$("#versionBadge").textContent=d.version||"v3";$("#switchSeconds").textContent=state.switchMs/1000}catch(e){$("#statusText").textContent=`読込エラー: ${e.message}`}}
async function market(){try{const r=await fetch(`./data/stocks.json?t=${Date.now()}`,{cache:"no-store"}),d=await r.json(),a=d.items||[];$("#marketPanel").hidden=!a.length;if(a.length)$("#ticker").innerHTML=a.map(x=>`<span class="tick">${esc(x.symbol)} ${esc(x.price??"—")} ${esc(x.change_pct??"—")}%</span>`).join("")}catch(e){$("#marketPanel").hidden=true}}
$("#prevBtn").onclick=()=>{state.index--;render();resetTimer()};$("#nextBtn").onclick=()=>{state.index++;render();resetTimer()};$("#pauseBtn").onclick=()=>{state.manualPaused=!state.manualPaused;setPause()};$("#focusModeBtn").onclick=()=>{state.focus=!state.focus;document.body.classList.toggle("focus-mode",state.focus)};$("#refreshBtn").onclick=()=>{news();market()};$("#searchInput").oninput=e=>{state.query=e.target.value.trim().toLowerCase();state.index=0;apply();render()};$("#sortSelect").onchange=e=>{state.sort=e.target.value;state.index=0;apply();render()};
$("#primaryCard").addEventListener("mouseenter",()=>{state.hoverPaused=true;setPause()});$("#primaryCard").addEventListener("mouseleave",()=>{state.hoverPaused=false;setPause()});
setInterval(()=>$("#clock").textContent=new Date().toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit",second:"2-digit"}),1000);
news();market();setInterval(news,5*60*1000);setInterval(market,5*60*1000);
